name:  simple_text_editor
description: >
  A simple rich text editor library that was created for a dartwatch 
  blog post, see http://blog.dartwatch.com 
author: Chris Buckett <chrisbuckett@gmail.com>
version: 0.0.1
homepage: http://blog.dartwatch.com

#dependencies:
#  js: any
#  unittest: { sdk: unittest }
